"""empty message

Revision ID: 1379cefac9f5
Revises: 6ab784f18ca0
Create Date: 2024-02-23 01:44:11.446349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1379cefac9f5'
down_revision = '6ab784f18ca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
